name: CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Make Directory
      run: mkdir deploy

    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    - name: Copy scripts
      run: cp ./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./demo.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./demo.zip s3://${{ secrets.AWS_S3_BUCKET }}/

    - name: Deploy
      run: |
        aws deploy create-deployment \
        --application-name demo \
        --deployment-group-name demo-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=demo.zip \
        --region ap-northeast-2